### ISSUE TITLE
The coding error in "Line 128 in model.py" 

### ISSUE THREAD

**Issue by yaoodng7** [YorkNishi999/ganite_pytorch#3]
Hi, thank you for your implementation of GANITE with Pytorch. However, there may be some error. Such as in "Line 128 of model.py", every layer compute the same h1 representation, is that true?

**Comment by YorkNishi999** [comment]
@yaoodng7 Thank you for your comment! I personally think that, considering the lines 94-101, the layers seems to be properly stacked. If you have an idea to fix, you can commit your code through the issue. If you have any other questions, please let me know!


<img width="442" alt="image" src="https://github.com/YorkNishi999/ganite_pytorch/assets/34223649/00a546e9-6bf6-4c57-b4ae-56b3c502bf27">
